Переписал метод подсчета постов , также нашел конфиг файл для Postclient
AlexeiZhurov/EBSUserservice pull request #3
Opened 2022-07-19 07:33 UTC by AlexeiZhurov

2022-07-20 20:29 UTC, MadridianFox commented on app/Console/Commands/getUserPost.php
> +            $total = count($respons);
Это неправильный код.
Метод getData() возвращает объект ответа, у которого нужно вызывать его методы чтобы получить значение. Если структура вложенная, то там тоже будут объекты.
Нужно понимать что лежит у тебя в переменной.
Если не знаешь - делай var_dump() или dump() или используй отладчик, или читай код.

2022-07-20 20:30 UTC, MadridianFox commented on postgres/data/postmaster.pid
> +1
Папка postgres/data не должна попадать в гит.

2022-07-20 20:34 UTC, MadridianFox requested changes
1) есть замечания по коду
2) в репозиторий попали лишние файлы
3) в этом ПР я вижу исправления замечаний, сделанных для другого ПР, который сейчас закрыт и смержен без исправления замечаний.
Это неправильно. ПР это запрос слияния одной ветки в другую ветку.
Ветка - это изменения кода по какой-то задаче. Если ты допустил ошибку - ты должен исправить её в той же ветке, чтобы изменения были видны в том же ПР. Только  когда все  замечания будут исправлены ПР можно будет закрывать.

2022-07-20 20:51 UTC, MadridianFox commented on app/Console/Commands/getUserPost.php
> +        $respons = $api->searchPosts($request)->getData();
В классе Command не должно быть кода.
Тут может быть только разбор аргументов, вывод результата и вызов action.
Это как контроллер, только не для http запросов, а для консольных команд.
И Command и Controller не должны ничего делать самостоятельно. Они должны делегировать задачу какому-нибудь Action или Query и заниматься приёмом и передачей аргументов/результата

2022-07-22 07:40 UTC, AlexeiZhurov commented
Я могу закрывать PR?

2022-07-22 08:26 UTC, merged